<a href="https://colab.research.google.com/github/Dashnyam7/DIC_assignment/blob/main/Ensemble_learning_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
dataset = pd.read_csv("train.csv")
X = dataset.loc[:, ['GrLivArea', 'YearBuilt']]
y = dataset.loc[:, ['SalePrice']]
X = X.values
y = y.values
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

# [Problem 1] Scratch implementation of blending

### What is blending

Blending is a method of independently learning N diverse models, weighting the estimation results, and adding them together. The simplest is to take the average. Diverse models are created by changing the following conditions.

-Techniques (e.g. linear regression, SVM, decision trees, neural networks, etc.)

-Hyperparameters (e.g. SVM kernel type, initial weights, etc.)

-How to preprocess the input data (e.g. normalization, logarithmic transformation, PCA, etc.)
Importantly, each model is very different.

Blending for regression problems is so simple that scikit-learn does not provide it.

For classification problems, majority vote is used. VotingClassifier is provided in scikit-learn because it is more complicated than regression problems.

In [25]:
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LinearRegression
svc = SVC() 
rf = RandomForestClassifier()
tree = DecisionTreeClassifier(max_depth=3)
vc = VotingClassifier(estimators=[('svc', svc), ('rf', rf), ('tree', tree)], voting='hard')
vc = vc.fit(X_train, y_train)
pred = vc.predict(X_test)
pred

/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([173000, 100000, 178000, 100000, 178000, 136000, 178000, 109000,
        80000, 160000, 178000, 100000, 178000, 178000, 178000, 135000,
       100000,  80000, 147400, 178000, 178000, 159895, 178000, 100000,
        80000, 178000, 109000, 140000, 100000, 140000, 135000, 135000,
       140000, 178000, 100000, 178000, 140000, 100000, 172500, 178000,
       178000, 140000, 140000, 135000, 178000, 140000, 140000, 178000,
       140000, 190000, 123500, 100000, 178000, 100000, 178000, 178000,
       135000, 178000, 135000, 178000, 140000, 178000, 100000, 135000,
       178000, 135000, 178000, 100000, 178000, 140000, 140000, 178000,
       140000, 135000, 135000, 178000, 140000, 100000, 140000, 178000,
       178000, 100000, 140000, 140000, 135000, 164000, 135000, 135000,
       135000, 178000, 135000, 178000, 178000,  82000, 135000, 140000,
       140000, 178000, 130500, 178000, 140000, 178000, 178000, 130500,
       178000, 136000, 135000, 178000,  99500, 140000, 140000, 140000,
      

In [26]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, pred))

0.003424657534246575


In [30]:
tree.fit(X_train, y_train)
pred2 = tree.predict(X_test)
print(accuracy_score(y_test, pred2))

0.010273972602739725


# [Problem 2] Scratch implementation of bagging

### What is bagging

Bagging is a method of diversifying the selection of input data. Create N types of subsets ( bootstrap samples ) by randomly extracting from the training data while allowing duplication . Train N models with them and average the estimation results. Unlike blending, it does not change the weighting of each.

In [36]:
from sklearn.ensemble import BaggingRegressor
regr = BaggingRegressor(base_estimator=svc,n_estimators=10, random_state=0).fit(X_train, y_train)
pred3 = regr.predict(X_test)
pred3

/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_bagging.py:429: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return column_or_1d(y, warn=True)


array([147550. , 126610. , 158320. , 104547.1, 213180. , 149379. ,
       182349. , 112682.1, 102907.1, 123980. , 182349. ,  83964.3,
       167540. , 178639. , 182349. , 126930. , 107867.1, 103767.1,
       158595. , 175524. , 173389. , 158595. , 158530. , 100442.1,
       125190. , 205215. , 120790. , 123685. ,  93024.3, 137135. ,
       127830. , 125330. , 128365. , 177148. ,  97362.1, 156180. ,
       122960. , 100442.1, 162370. , 178639. , 158530. , 157410. ,
       143910. , 127830. , 182349. , 132180. , 130635. , 177314. ,
       137135. , 163125.3, 125330. , 104547.1, 146825. ,  83964.3,
       182349. , 190274. , 127830. , 190274. , 115270. , 158595. ,
       146210. , 183046.5, 110167.1, 120790. , 182349. , 156280. ,
       167270. , 125190. , 188218. , 134028.2, 129385. , 156180. ,
       138020. , 125330. , 126440.4, 182349. , 128785. , 107867.1,
       138480. , 184948. , 151040. , 117917.1, 164970. , 127365. ,
       127830. , 176989. , 129830. , 126930. , 127830. , 15853

# [Problem 3] Scratch implementation of stacking

### What is stacking

The stacking procedure is as follows. Stacking is valid if there are at least stage 0 and stage 1, so please implement it. First
$K_0$=3, $M_0$=2
to a degree.

### 《When learning》

(stage $0$ )

-Split the training data into $K_0$ pieces.

-You can create $K_0$ combinations of $(K_0 - 1)$ splits as training data and the remaining $1$ as estimation data.

-Prepare $K_0$ instances of a model and train it using different training data.

-For each trained model, input the remaining $1$ data for estimation that are not used and obtain estimated values. (This is called blend data)

-In addition, prepare $K_0$ instances of different models and do the same thing. If you have $M_0$ models, you will get $M_0$ blended data.

(stage $n$ )

-Consider the blended data of stage $n-1$ as training data with $M_{n-1}$-dimensional features, and divide it into $K_n$ pieces. The same applies hereinafter.
(Stage $N$ ) * Last stage

-$M_{N-1}$ pieces of blended data of stage $N-1$ are used as inputs for $M_{N-1}$ dimensional features to train one type of model. This becomes the model for the final estimation.

### "Presumption"

(stage $0$ )

Input test data into $K_0×M_0$ trained models and obtain $K_0×M_0$ estimates. Calculate the average value of this on the $K_0$ axis to obtain data with $M_0$-dimensional feature values. (called blend test)


(stage $n$ )

We input the blended tests obtained in stage $n-1$ into $K_n×M_n$ trained models and obtain $K_n×M_n$ estimates. Calculate the average value of this on the $K_n$ axis to obtain data with $M_0$-dimensional feature values. (called blend test)


(Stage $N$ ) * Last stage

Input the blended test obtained in stage $N-1$ into the trained model and get an estimate.

In [48]:
from sklearn.ensemble import StackingRegressor, RandomForestRegressor
sr = StackingRegressor(estimators=[('lr', lr)], final_estimator=RandomForestRegressor())
sr = sr.fit(X_train, y_train)
pred4 = sr.predict(X_test)
pred4

/usr/local/lib/python3.8/dist-packages/sklearn/ensemble/_stacking.py:758: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([142827.64      , 140077.25      , 151424.        , 115609.        ,
       341042.21      , 217448.86      , 249586.06      , 110901.25      ,
       107035.        , 141879.46      , 233415.        ,  90129.        ,
       180560.6       , 239486.4       , 215475.        , 133990.        ,
       114970.        , 123308.5       , 178800.        , 265679.        ,
       195155.        , 140000.        , 186849.        , 112131.        ,
       132818.25      , 412750.        , 110547.        , 134629.        ,
       112994.        , 134730.        , 136350.4       , 146174.        ,
       180020.        , 273264.        , 105035.        , 208365.        ,
       132965.        , 111776.        , 200174.55      , 239241.        ,
       174436.41666667, 152575.        , 165260.        , 116920.        ,
       219037.        , 146890.        , 148837.4       , 204809.        ,
       152630.        , 179460.        , 155428.        ,  92765.        ,
       142594.        ,  

In [49]:
print(accuracy_score(y_test, pred2))

0.010273972602739725
